.TH SHELL 1 "25 March 2024" "Version 1.0" "Shell User Manual"
.SH NAME
Simple Shell \- command interpreter
.SH SYNOPSIS
.B shell
.RI [ command_string ]
.SH DESCRIPTION
The shell is a command language interpreter. This is the basic operation of a Unix-style operating system.
.SH OPTIONS
.IP "not yet listed"
Execute the command_string.
.SH EXAMPLES
.IP "shell \"echo Hello, World!\""
This will print 'Hello, World!' to the console.
.SH SEE ALSO
.BR bash (1),
.BR sh (1)
.SH HISTORY
    2024 - Originally written by Atlas School students
    Davey Hays <david.c.hays.iii@gmail.com> and Chase Sparks <charles.sparks@atlasschool.com>

    This was school project to help us better understand the skills and nature of Programming.
    It's intended purpose was to give us a feel for all that goes into such projects.
.SH BUGS
Plenty of bugs, some unkown.
.SH AUTHOR
Davey Hays <david.c.hays.iii@gmail.com>
Chase Sparks <charles.sparks@atlasschool.com>
